version: '3'
services:
  # Config Server
  configsvr:
    image: mongo:4.4
    container_name: configsvr
    command: mongod --configsvr --replSet configReplSet --bind_ip_all
    ports:
      - "27019:27019"
    volumes:
      - /data/configdb
    networks:
      - mongonet

  # Shard 1
  shard1:
    image: mongo:4.4
    container_name: shard1
    command: mongod --shardsvr --replSet shardReplSet --bind_ip_all
    ports:
      - "27018:27018"
    volumes:
      - /data/db
    networks:
      - mongonet

  # Shard 2
  shard2:
    image: mongo:4.4
    container_name: shard2
    command: mongod --shardsvr --replSet shardReplSet --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    networks:
      - mongonet

  # Mongos Router
  mongos:
    image: mongo:4.4
    container_name: mongos
    command: mongos --configdb configReplSet/configsvr:27019 --bind_ip_all
    ports:
      - "28017:27017"
    networks:
      - mongonet

networks:
  mongonet:
    driver: bridge
