version: '3'
services:
  # Shard 3
  shard3:
    image: mongo:4.4
    container_name: shard3
    command: mongod --shardsvr --replSet shardReplSet --bind_ip_all
    ports:
      - "27020:27017"
    volumes:
      - /data/db
    networks:
      - mongonet

networks:
  mongonet:
    driver: bridge
